tema1:
	mpicc tema1.c -o tema1 && mpirun -np 2 tema1

tema2:
	mpicc tema2.c -o tema2 && mpirun -np 2 tema2

sendIsBlocking:
	mpicc sendIsBlocking.c -o sendIsBlocking && mpirun -np 2 sendIsBlocking

trei:
	mpicc trei.c -o trei && mpirun -np 10 trei

patru:
	mpicc patru.c -o patru && mpirun -np 12 patru

cinci:
	mpicc cinci.c -o cinci && mpirun -np 12 cinci

clean:
	clear && rm -rf tema1 sendIsBlocking tema2 trei patru cinci