tema:
	mpicc tema.c -o tema && mpirun -np 2 tema

unu:
	mpicc unu.c -o unu && mpirun -np 2 unu

doi:
	mpicc doi.c -o doi && mpirun -np 4 doi

trei:
	mpicc trei.c -o trei && mpirun -np 4 trei

patru:
	mpicc patru.c -o patru && mpirun -np 4 patru

cinci:
	mpicc cinci.c -o cinci && mpirun -np 5 cinci

sase:
	mpicc sase.c -o sase && mpirun -np 4 sase

sapte:
	mpicc sapte.c -o sapte && mpirun -np 2 sapte

opt:
	mpicc opt.c -o opt && mpirun -np 12 opt

clean:
	clear && rm -rf tema unu doi trei patru cinci sase sapte opt